### ISSUE TITLE
Missing Tailwind utility classes?

### ISSUE THREAD

**Issue by frankstallone** [Set-Creative-Studio/cube-boilerplate#1]
Been loving this so far, can't thank you enough for doing this! 

I have ran into a few situations where I would have expected to see Tailwind classes working fine but they don't autocomplete in VSCode, and produce no CSS when added to DOM elements. Examples are `h-auto`, `aspect-video`, `fill-current`.

I have been digging through your blog post, and the Tailwind config but can't seem to figure out what's causing this. Other classes work just fine. What am I missing? 😄

**Comment by wongjn** [comment]
Consider providing a project that reproduces the unexpected behavior.

**Comment by frankstallone** [comment]
It's 100% the empty `presets` array in the config. 😄

**Comment by Andy-set-studio** [comment]
Ah yeh that was set like that to slim down stuff as much as possible. We're only using Tailwind utilities to apply design tokens (with the odd flex property too), so we don't need that stuff in the boilerplate!

**Comment by frankstallone** [comment]
Thanks for sharing your use case for this empty array!

From my quick analysis, removing this added nothing to the final CSS file size.
