### ISSUE TITLE
Question: Dark mode

### ISSUE THREAD

**Issue by rol4nd909** [Set-Creative-Studio/cube-boilerplate#10]
It's not an issue, but I'm really wondering how you handle darkmode with the way of working in this boilerplate?
I hope you can/will give some insights of it.

**Comment by Andy-set-studio** [comment]
Howdy! Definitely not something I’ll add to this repo because dark mode is very specific. I am publishing a post about how to approach theming soon on https://piccalil.li soon though!

**Comment by rol4nd909** [comment]
It was more like a question and understand it's not supposed to be in this repo. Is the post then focused on this way of using tailwind and cube css? Because that is what I'm most curious about at the moment ;)

**Comment by Andy-set-studio** [comment]
Here it is https://piccalil.li/blog/how-were-approaching-theming-with-modern-css
