### ISSUE TITLE
Missing sidebar RTL exception

### ISSUE THREAD

**Issue by csorrentino** [Set-Creative-Studio/cube-boilerplate#8]
I'm not quite sure if this is a bug or how it was intended, but I thought I'd point out that the comments in the sidebar composition include this line which doesn't have a matching exception:

```
EXCEPTIONS
.sidebar[data-direction='rtl']: flips the sidebar to be on the right 
```

Is this intended to be a hint for how this could be used or is something actually missing?

**Comment by Andy-set-studio** [comment]
Ah this is a carry-over from a project, so that comment just needs removing
